USE MiniFacebook
-- Solution: SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRANSACTION
	SELECT post_shares FROM Posts WHERE user_id=1;
	WAITFOR DELAY '00:00:10';
	SELECT post_shares FROM Posts WHERE user_id=1;
	COMMIT;