USE SmartHomes
-- Solution: SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRANSACTION
	SELECT h_name FROM Homes WHERE r_id=1
	WAITFOR DELAY '00:00:10'
	SELECT h_name FROM Homes WHERE r_id=1
	COMMIT;